# Generated by Django 6.0.2 on 2026-02-24 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Klinika haqqinda magliwmat')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='YouTube video linki')),
                ('image', models.ImageField(upload_to='about/', verbose_name='Tiykargi bettegi suwret')),
            ],
            options={
                'verbose_name': 'Klinika haqqinda',
                'verbose_name_plural': 'Klinika haqqinda',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='soraw')),
                ('answer', models.TextField(verbose_name='juwap')),
            ],
            options={
                'verbose_name': 'Kop beriletugin soraw',
                'verbose_name_plural': 'Kop beriletugin sorawlar',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Suwret')),
                ('caption', models.CharField(blank=True, max_length=100, verbose_name='Suwret ati (optional)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Galereya',
                'verbose_name_plural': 'Galereya',
            },
        ),
    ]
