# Generated by Django 6.0.2 on 2026-03-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_about_text1_text_about_text1_title_about_text2_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('job', models.CharField(max_length=100)),
                ('comment', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
            ],
        ),
    ]
