# Generated by Django 6.0.2 on 2026-02-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Servis ati')),
                ('description', models.TextField(verbose_name='servis haqqinda magliwmat')),
                ('icon', models.CharField(help_text='Bootstrap icon klassi (misali: bi-heart-pulse)', max_length=50)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='twitter',
        ),
    ]
